name: "Lambda deployment"
on: 
    push:
        branches: 
            - master
            - collaborate

jobs: 
    deployment:
        runs-on: ubuntu-latest
        steps: 
            - name: "Checkout the repo"
              uses: actions/checkout@v4

            - name: "Configure AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-region: ${{ secrets.AWS_REGION }}
                aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}

            - name: "Checks if this works"
              run: | 
                echo "Everything works fine"
