name: "Lambda deployment"
on: 
    push:
        branches: 
            - master
            - collaborate

jobs: 
    deployment:
        runs-on: ubuntu-latest
        steps: 
            - name: "Checkout the repo"
              uses: actions/checkout@v4

            - name: "Configure AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-region: ${{ secrets.AWS_REGION }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}

            - name: "Creates a role"
              run: |
                #aws iam create-role --role-name testrole8 --assume-role-policy-document file://sample.json

            - name: "Creates a function"
              run: |
                zip -j init.zip ./initcode.py

                aws lambda create-function --function-name testfunction --runtime python3.9 --role arn:aws:iam::373550324447:role/testrole8 --zip-file fileb://init.zip
                test.zip 
            - name: "Checks if this works"
              run: | 
                echo "Everything works fine"

            - name: 'Convert to zip format'
              run: | 
                zip -j test.zip ./code.py

                #aws lambda update-function-code --function-name corecycloboldlambda100 --zip-file fileb://test.zip
